# Generated by Django 4.2.8 on 2024-08-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_haribhakt_mandal_delete_mandal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Haribhakt",
        ),
    ]
